name: rsync-core22
version: 3.4.1
summary: Utility for transferring and syncing files between computers and drives
description: |
  Rsync is a utility for efficiently transferring and synchronizing files
  between a computer and a storage drive and across networked computers by
  comparing the modification times and sizes of files.

license: GPL-3.0+

grade: stable
confinement: strict
base: core22

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x

apps:
    rsync:
        command: usr/local/bin/rsync
        plugs: [network, home, removable-media, ssh-keys]

parts:
    rsync:
        plugin: autotools
        source: https://download.samba.org/pub/rsync/src/rsync-3.4.1.tar.gz
        source-type: tar
        source-checksum: sha256/2924bcb3a1ed8b551fc101f740b9f0fe0a202b115027647cf69850d65fd88c52
        build-packages:
          - gcc
          - g++
          - gawk
          - autoconf
          - automake
          - python3-cmarkgfm
          - acl
          - libacl1-dev
          - attr
          - libattr1-dev
          - libxxhash-dev
          - libzstd-dev
          - liblz4-dev
          - libssl-dev
